
#include "script_component.hpp";

diag_log "tScripts Logging: Detected RHS USAF, ACE. Switching equipment.";

call {	//Weapons
	BLU_PRIMARY_RIFLE = "arifle_MX_Black_F";
	BLU_PRIMARY_RIFLE_COMPACT = "arifle_MXC_Black_F";
	BLU_PRIMARY_RIFLE_GRENADIER = "arifle_MX_GL_Black_F";
	BLU_PRIMARY_RIFLE_AUTOMATIC = "arifle_MX_SW_Black_F";
	BLU_PRIMARY_RIFLE_MARKSMAN = "arifle_MXM_Black_F";
	BLU_PRIMARY_MACHINEGUN = "LMG_Mk200_F";

	BLU_SECONDARY_PISTOL = "hgun_P07_F";

	BLU_LAUNCHER_LAT = "";
	BLU_LAUNCHER_HAT = "launch_MRAWS_green_F";
};

call {	//Weapon Attachments
	BLU_OPTIC_RCO = "optic_hamr";
	BLU_OPTIC_CCO = "optic_holosight_blk_f";
	BLU_OPTIC_MGO = "optic_hamr";
	BLU_OPTIC_MARK = "optic_sos";
	BLU_OPTIC_LAUNCHER = "";

	BLU_RAIL_LASER_TOP = "acc_pointer_ir";
	BLU_RAIL_LASER_SIDE = "acc_pointer_ir";
	BLU_RAIL_FLASH = "acc_flashlight";

	BLU_MUZZLE_RIFLE_FLASH = "";
	BLU_MUZZLE_MACHINEGUN_FLASH = "";
	BLU_MUZZLE_SUPPRESSOR = "muzzle_snds_65_ti_blk_f";

	BLU_UNDERBARREL_RIFLE_AUTOMATIC = "bipod_01_f_blk";
	BLU_UNDERBARREL_BIPOD = "bipod_01_f_blk";
};

call {//Magazines
	BLU_MAGAZINES_RIFLE = "30Rnd_65x39_caseless_black_mag";
	BLU_MAGAZINES_RIFLE_TRACER = "30Rnd_65x39_caseless_black_mag_Tracer";
	BLU_MAGAZINES_RIFLE_AUTOMATIC = "100Rnd_65x39_caseless_black_mag";
	BLU_MAGAZINES_MACHINEGUN = "200Rnd_65x39_cased_Box";
	BLU_MAGAZINES_GRENADIER_HE = "1Rnd_HE_Grenade_shell";
	BLU_MAGAZINES_GRENADIER_SMOKE = "1Rnd_SmokeRed_Grenade_shell";
	BLU_MAGAZINES_GRENADIER_FLARE = "UGL_FlareCIR_F";
	BLU_MAGAZINES_RIFLE_MARKSMAN = "30Rnd_65x39_caseless_black_mag";

	BLUE_MAGAZINES_PISTOL = "16Rnd_9x21_Mag";

	BLU_MAGAZINES_HAT_AT = "MRAWS_HEAT_F";
	BLU_MAGAZINES_HAT_HE = "MRAWS_HE_F";
};

call {	//Grenades
	BLU_GRENADE_FRAG = "HandGrenade";
	BLU_GRENADE_SMOKE = "SmokeShell";
	BLU_GRENADE_SMOKE_BLUE = "SmokeShellBlue";
	BLU_GRENADE_CHEM = "Chemlight_blue";
	BLU_GRENADE_CHEM_YELLOW = "Chemlight_yellow";
	BLU_GRENADE_CHEM_RED = "Chemlight_red";
	BLU_GRENADE_IR = "B_IR_Grenade";
};

call {	//Items
	BLU_MEDICAL_BASIC = "FirstAidKit";
	BLU_MEDICAL_ADVANCED = "";
	BLU_MEDICAL_TOURNIQUET = "";
	BLU_MEDICAL_MORPHINE = "";
	BLU_MEDICAL_EPINEPHRINE = "";
	BLU_MEDICAL_SALINE = "";
	BLU_MEDICAL_SPLINT = "";
	BLU_MEDICAL_PAK = "";

	BLU_DAGR = "";

	BLU_NVG = "NVGoggles_INDEP";
	BLU_BINO = ["Binocular","","","",[],[],""];
	BLU_ITEMS = ["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""];
};

call {	//Uniforms
	BLU_HELMET_LEADER = "H_HelmetSpecB";
	BLU_HELMET_TROOPER = "H_HelmetB_light";
	BLU_HELMET_CREWMAN = "H_HelmetCrew_B";

	BLU_UNIFORM = "U_B_CombatUniform_mcam";
	BLU_UNIFORM_CONTENTS = [BLU_UNIFORM,[[BLU_MEDICAL_BASIC,5]]];
};

call {	//Vests
	BLU_VEST_SQUADLEADER = "V_PlateCarrierGL_rgr";
	BLU_VEST_TEAMLEADER = "V_PlateCarrierGL_rgr";
	BLU_VEST_TEAMLEADER_ALT = "V_PlateCarrierGL_rgr";
	BLU_VEST_AUTOMATICRIFLEMAN = "V_PlateCarrier2_rgr";
	BLU_VEST_GRENADIER = "V_PlateCarrier2_rgr";
	BLU_VEST_RIFLEMAN = "V_PlateCarrier2_rgr";
	BLU_VEST_RIFLEMAN_ALT = "V_PlateCarrier2_rgr";
	BLU_VEST_MACHINEGUNNER = "V_PlateCarrier2_rgr";
	BLU_VEST_MARKSMAN = "V_PlateCarrier2_rgr";
	BLU_VEST_MEDIC = "V_PlateCarrier2_rgr";
	BLU_VEST_CREWMAN = "V_PlateCarrier2_rgr";
};

call {	//Packs
	BLU_PACK_ASSAULTPACK = "B_AssaultPack_mcamo";
	BLU_PACK_TACTICALPACK = "B_TacticalPack_mcamo";
	BLU_PACK_KITBAG = "B_Kitbag_mcamo";
	BLU_PACK_CARRYALL = "B_Carryall_mcamo";

	BLU_PACK_RATELO = BLU_PACK_ASSAULTPACK;
};

call {	//Assemblies/Contents
	call {	//Weapons
		BLU_WEAP_SYS_RIFLE_LEADER = [BLU_PRIMARY_RIFLE,BLU_MUZZLE_RIFLE_FLASH,BLU_RAIL_LASER_TOP,BLU_OPTIC_RCO,[BLU_MAGAZINES_RIFLE_TRACER,30],[],""];
		BLU_WEAP_SYS_RIFLE_TROOPER = [BLU_PRIMARY_RIFLE,BLU_MUZZLE_RIFLE_FLASH,BLU_RAIL_LASER_TOP,BLU_OPTIC_CCO,[BLU_MAGAZINES_RIFLE,30],[],""];
		BLU_WEAP_SYS_RIFLE_COMPACT = [BLU_PRIMARY_RIFLE_COMPACT,BLU_MUZZLE_RIFLE_FLASH,BLU_RAIL_LASER_TOP,BLU_OPTIC_CCO,[BLU_MAGAZINES_RIFLE,30],[],""];
		BLU_WEAP_SYS_RIFLE_GRENADIER = [BLU_PRIMARY_RIFLE_GRENADIER,BLU_MUZZLE_RIFLE_FLASH,BLU_RAIL_LASER_TOP,BLU_OPTIC_CCO,[BLU_MAGAZINES_RIFLE,30],[],""];
		BLU_WEAP_SYS_RIFLE_AUTOMATIC = [BLU_PRIMARY_RIFLE_AUTOMATIC,BLU_MUZZLE_RIFLE_FLASH,BLU_RAIL_LASER_SIDE,BLU_OPTIC_MGO,[BLU_MAGAZINES_RIFLE_AUTOMATIC,100],[],BLU_UNDERBARREL_RIFLE_AUTOMATIC];

		BLU_WEAP_SYS_RIFLE_MARKSMAN = [BLU_PRIMARY_RIFLE_MARKSMAN,"",BLU_RAIL_LASER_SIDE,BLU_OPTIC_MARK,[BLU_MAGAZINES_RIFLE_MARKSMAN,30],[],BLU_UNDERBARREL_RIFLE_AUTOMATIC];
		BLU_WEAP_SYS_RIFLE_MACHINEGUN = [BLU_PRIMARY_MACHINEGUN,BLU_MUZZLE_MACHINEGUN_FLASH,BLU_RAIL_LASER_SIDE,BLU_OPTIC_MGO,[BLU_MAGAZINES_MACHINEGUN,200],[],""];

		BLU_WEAP_SYS_PISTOL = [BLU_SECONDARY_PISTOL,"","","",[BLUE_MAGAZINES_PISTOL,16],[],""];

		BLU_WEAP_SYS_LAT = [BLU_LAUNCHER_LAT,"","","",[],[],""];
		BLU_WEAP_SYS_HAT = [BLU_LAUNCHER_HAT,"","",BLU_OPTIC_LAUNCHER,[BLU_MAGAZINES_HAT_AT, 1],[],""];
	};
	call { // Contents
		call {	//Rifleman
			BLU_VEST_CONTENTS_RIFLEMAN = [BLU_VEST_RIFLEMAN,[[BLU_MAGAZINES_RIFLE,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_RIFLEMAN = [BLU_PACK_ASSAULTPACK,[]];
		};
		call {	//Grenadier
			BLU_VEST_CONTENTS_GRENADIER = [BLU_VEST_GRENADIER,[[BLU_MAGAZINES_RIFLE,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_GRENADIER = [BLU_PACK_ASSAULTPACK,[[BLU_MAGAZINES_GRENADIER_HE,11,1],[BLU_MAGAZINES_GRENADIER_SMOKE,4,1],[BLU_MAGAZINES_GRENADIER_FLARE,4,1]]];
		};
		call {	//Automatic Rifleman
			BLU_VEST_CONTENTS_AUTOMATICRIFLEMAN = [BLU_VEST_AUTOMATICRIFLEMAN,[[BLU_MAGAZINES_RIFLE_AUTOMATIC,3,100],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_AUTOMATICRIFLEMAN = [BLU_PACK_ASSAULTPACK,[[BLU_MAGAZINES_RIFLE_AUTOMATIC,2,100]]];
		};
		call {	//Combat Life Saver
			BLU_VEST_CONTENTS_COMBATLIFESAVER = [BLU_VEST_MEDIC,[[BLU_MAGAZINES_RIFLE,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_GRENADE_CHEM_YELLOW,4,1],[BLU_GRENADE_CHEM_RED,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_COMBATLIFESAVER = [BLU_PACK_ASSAULTPACK,[[BLU_MEDICAL_BASIC,20]]];
		};
		call {	//Marksman
			BLU_VEST_CONTENTS_MARKSMAN = [BLU_VEST_MARKSMAN,[[BLU_MAGAZINES_RIFLE_MARKSMAN,7,30],[BLUE_MAGAZINES_PISTOL,3,16],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_MARKSMAN = [BLU_PACK_ASSAULTPACK,[[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1]]];
		};
		call { //Team Leader
			BLU_VEST_CONTENTS_TEAMLEADER = [BLU_VEST_TEAMLEADER,[[BLU_MAGAZINES_RIFLE_TRACER,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_TEAMLEADER = [BLU_PACK_ASSAULTPACK,[[BLU_GRENADE_SMOKE_BLUE,2,1],[BLU_GRENADE_CHEM,2,1],[BLU_GRENADE_IR,2,1]]];
		};
		call { //Squad Leader
			BLU_VEST_CONTENTS_SQUADLEADER = [BLU_VEST_SQUADLEADER,[[BLU_MAGAZINES_RIFLE_TRACER,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_SQUADLEADER = BLU_PACK_CONTENTS_TEAMLEADER;
		};
		call {	//Machinegun Assistant
			BLU_VEST_CONTENTS_MACHINEGUNASSISTANT = [BLU_VEST_TEAMLEADER_ALT,[[BLU_MAGAZINES_RIFLE_TRACER,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_MACHINEGUNASSISTANT = [BLU_PACK_TACTICALPACK,[[BLU_MAGAZINES_MACHINEGUN,6,200],[BLU_GRENADE_SMOKE_BLUE,2,1],[BLU_GRENADE_CHEM,2,1],[BLU_GRENADE_IR,2,1]]];
		};
		call {	//Machinegunner
			BLU_VEST_CONTENTS_MACHINEGUNNER = [BLU_VEST_MACHINEGUNNER,[[BLU_MAGAZINES_MACHINEGUN,2,200],[BLUE_MAGAZINES_PISTOL,3,16],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_MACHINEGUNNER = [BLU_PACK_ASSAULTPACK,[[BLU_MAGAZINES_MACHINEGUN,3,200]]];
		};
		call {	//Machinegun Ammo Bearer
			BLU_VEST_CONTENTS_MACHINEGUNAMMOBEARER = BLU_VEST_CONTENTS_RIFLEMAN;
			BLU_PACK_CONTENTS_MACHINEGUNAMMOBEARER = [BLU_PACK_TACTICALPACK,[[BLU_MAGAZINES_MACHINEGUN,7,200]]];
		};
		call {	//Anti Tank Gunner
			BLU_VEST_CONTENTS_ATGUNNER = BLU_VEST_CONTENTS_RIFLEMAN;
			BLU_PACK_CONTENTS_ATGUNNER = [BLU_PACK_ASSAULTPACK,[[BLU_MAGAZINES_HAT_HE,2,1]]];
		};
		call {	//Anti Tank Ammo Bearer
			BLU_VEST_CONTENTS_ATAMMOBEARER = BLU_VEST_CONTENTS_RIFLEMAN;
			BLU_PACK_CONTENTS_ATAMMOBEARER = [BLU_PACK_TACTICALPACK,[[BLU_MAGAZINES_HAT_AT,1,1],[BLU_MAGAZINES_HAT_HE,2,1]]];
		};
		call {	//Platoon Medic
			BLU_VEST_CONTENTS_MEDIC = [BLU_VEST_RIFLEMAN,[[BLU_MAGAZINES_RIFLE,7,30],[BLU_GRENADE_FRAG,2,1],[BLU_GRENADE_SMOKE,4,1],[BLU_GRENADE_SMOKE_BLUE,2,1],[BLU_GRENADE_CHEM_YELLOW,4,1],[BLU_GRENADE_CHEM_RED,4,1],[BLU_NVG,1]]];
			BLU_PACK_CONTENTS_MEDIC = [BLU_PACK_TACTICALPACK,[["Medikit",1],[BLU_MEDICAL_BASIC,20]]];
		};
		call {	//Crewman
			BLU_VEST_CONTENTS_CREWMAN = BLU_VEST_CONTENTS_RIFLEMAN;
			BLU_PACK_CONTENTS_CREWMAN = [BLU_PACK_ASSAULTPACK,[["MineDetector",1],["ToolKit",1]]];
		};
		call {	//RATELO
			BLU_VEST_CONTENTS_RATELO = BLU_VEST_CONTENTS_RIFLEMAN;
			BLU_PACK_CONTENTS_RATELO = BLU_PACK_CONTENTS_RIFLEMAN;
		};
	};
};
