
#include "script_macros.hpp"

#define PREFIX tScripts

#define iconManCommander3 "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManCommander3_ca'/>"
#define iconManCommander2 "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManCommander2_ca'/>"
#define iconManCommander "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManCommander_ca'/>"
#define iconManOfficer "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManOfficer_ca'/>"
#define iconManLeader "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManLeader_ca'/>"
#define iconManMG "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManMG_ca'/>"
#define iconManAT "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManAT_ca'/>"
#define iconMan "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconMan_ca'/>"
#define iconManMedic "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManMedic_ca'/>"
#define iconManEngineer "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManEngineer_ca'/>"
#define iconManEOD "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManExplosive_ca'/>"
#define iconManRecon "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconManRecon_ca'/>"
#define iconAPC "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconAPC_ca'/>"
#define iconBackpack "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconBackpack_ca'/>"
#define iconCar "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCar_ca'/>"
#define iconCrate "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrate_ca'/>"
#define iconCrateAmmo "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateAmmo_ca'/>"
#define iconCrateGrenades "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateGrenades_ca'/>"
#define iconCrateLarge "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateLarge_ca'/>"
#define iconCrateLong "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateLong_ca'/>"
#define iconCrateOrdinance "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateOrd_ca'/>"
#define iconCrateSupply "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateSupp_ca'/>"
#define iconCrateVehicle "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateVeh_ca'/>"
#define iconCrateWeapons "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconCrateWpns_ca'/>"
#define iconFlag "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconLogic_ca'/>"
#define iconHelicopter "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconHelicopter_ca'/>"
#define iconParachute "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconParachute_ca'/>"
#define iconPlane "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconPlane_ca'/>"
#define iconShip "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconShip_ca'/>"
#define iconStaticMG "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconStaticMG_ca'/>"
#define iconStaticAA "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconStaticAA_ca'/>"
#define iconStaticMortar "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconStaticMortar_ca'/>"
#define iconTank "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconTank_ca'/>"
#define iconTruck "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconTruck_ca'/>"
#define iconVirtual "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconVirtual_ca'/>"
#define iconHeal "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconHeal_ca'/>"
#define iconExplosive "<img size='1' image='\a3\ui_f\data\Map\VehicleIcons\iconExplosive_ca'/>"

#define iconEdenMan "<img size='1' image='\a3\3den\data\Displays\Display3DEN\PanelRight\modeObjects_ca'/>"
#define iconEdenGroup "<img size='1' image='\a3\3den\data\Displays\Display3DEN\PanelRight\modeGroups_ca'/>"
#define iconEdenObjects "<img size='1' image='\a3\3den\data\Displays\Display3DEN\ToolBar\widget_local_ca'/>"
#define iconEdenRefresh "<img size='1' image='\a3\3den\data\Displays\Display3DEN\ToolBar\widget_rotation_off_ca'/>"
#define iconEdenVisionNormal "<img size='1' image='\a3\3den\data\Displays\Display3DEN\ToolBar\vision_normal_ca'/>"
#define iconEdenVisionNight "<img size='1' image='\a3\3den\data\Displays\Display3DEN\ToolBar\vision_nvg_ca'/>"
#define iconEdenVisionThermal "<img size='1' image='\a3\3den\data\Displays\Display3DEN\ToolBar\vision_ti_ca'/>"
#define iconEdenUp "<img size='1' image='\a3\3den\data\Displays\Display3DENSave\sort_up_ca'/>"
#define iconEdenDown "<img size='1' image='\a3\3den\data\Displays\Display3DENSave\sort_down_ca'/>"
#define iconEdenTreeExpand "<img size='1' image='\a3\3den\data\Displays\Display3DEN\tree_expand_ca'/>"
#define iconEdenTreeCollapse "<img size='1' image='\a3\3den\data\Displays\Display3DEN\tree_collapse_ca'/>"

#define colorHexWest "<t color='#004D9A'>"
#define colorHexEast "<t color='#800000'>"
#define colorHexGuer "<t color='#008000'>"
#define colorHexCiv "<t color='#660080'>"
#define colorHexUnknown "<t color='#B39A00'>"
#define colorHexGold "<t color='#FFD700'>"
